name: rich_clipboard
repository: https://github.com/BringingFire/rich_clipboard

packages:
  - rich_clipboard
  - rich_clipboard/example
  - rich_clipboard_platform_interface
  - rich_clipboard_macos
  - rich_clipboard_windows
  - rich_clipboard_linux
  - rich_clipboard_web
  - rich_clipboard_android
  - rich_clipboard_ios

scripts:
  analyze:
    exec: dart analyze .
  generate:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  test:
    run: flutter test -r expanded
    exec:
      fail-fast: true
    select-package:
      dir-exists: test

command:
  bootstrap:
    hooks:
      post: dart run melos run generate
