name: rich_clipboard_example
description: Demonstrates how to use the rich_clipboard plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rich_clipboard:
    path: ../

  gap: ^2.0.0
  flutter_widget_from_html: ^0.8.5
  # TODO: Switch to super_editor versions from pub.dev at some point
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown
  markdown: ^4.0.1
  html2md: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  rich_clipboard_macos:
    path: ../../rich_clipboard_macos
  rich_clipboard_windows:
    path: ../../rich_clipboard_windows
  rich_clipboard_linux:
    path: ../../rich_clipboard_linux
  rich_clipboard_web:
    path: ../../rich_clipboard_web
  rich_clipboard_platform_interface:
    path: ../../rich_clipboard_platform_interface
  # TODO: Remove this when super_editor publishes new versions to pub.dev
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: attributed_text

flutter:
  uses-material-design: true