name: rich_clipboard_example
description: Demonstrates how to use the rich_clipboard plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rich_clipboard:
    path: ../

  gap: ^2.0.0
  flutter_widget_from_html: ^0.8.5
  # TODO: Switch to super_editor versions from pub.dev at some point
  super_editor: 0.2.0
  super_editor_markdown: 0.2.0
  markdown: ^4.0.1
  html2md: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  # TODO: Remove these when super_editor publishes updated versions of all its packages
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      ref: 6c439f31f5047f9b2cecc011351cb321395fb795
      path: super_editor
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      ref: 6c439f31f5047f9b2cecc011351cb321395fb795
      path: super_editor_markdown
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: attributed_text

flutter:
  uses-material-design: true