name: rich_clipboard_windows
description: Windows implementation of the rich_clipboard plugin.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_windows
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_windows
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.15.0
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  rich_clipboard_platform_interface: ^0.0.1
  win32: ^2.5.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

dependency_overrides:
  rich_clipboard_platform_interface:
    path: ../rich_clipboard_platform_interface

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      windows:
        dartPluginClass: RichClipboardWindows
        pluginClass: none
